### ISSUE TITLE
[Bug]: Error 500 when ordering with offline payments

### ISSUE THREAD

**Issue by jarekmajcher** [Setono/SyliusAnalyticsPlugin#101]
### Plugin version

4.x

### Sylius version

1.13.x

### What happened?

When placing an order and selecting an offline payment method (e.g. bank transfer), I receive an error 500.

`Handling "Setono\SyliusAnalyticsPlugin\Message\Command\SendPurchaseEvent" failed: The order with id XX is not eligible for a Google Analytics purchase event to be sent.`

This is because the order has the payment status "awaiting_payment". This type is not included in the isEligible() function in the SendPurchaseEventHandler class.

By the way, it is quite dangerous to trigger 500 errors when placing an order. Can't we just only log such situations?

**Comment by loevgaard** [comment]
> By the way, it is quite dangerous to trigger 500 errors when placing an order. Can't we just only log such situations?

Agreed :)
