### ISSUE TITLE
Notice: Undefined index: search

### ISSUE THREAD

**Issue by igormukhingmailcom** [Setono/SyliusAnalyticsPlugin#13]
We have next error while running behat tests on one of our private projects (`E...000`):

`Notice: Undefined index: search in vendor/setono/sylius-analytics-plugin/src/EventListener/ViewSearchResultsEventListener.php line 25` (see https://github.com/Setono/SyliusAnalyticsPlugin/blob/f2fbb9184fa39cbdde7f09dc0d38da6e71377e5c/src/EventListener/ViewSearchResultsEventListener.php#L25)

So we should add some check there.

**Comment by loevgaard** [comment]
Will be removed in next update
