### ISSUE TITLE
[Bug]: GA events are not triggered 

### ISSUE THREAD

**Issue by ajayplanet** [Setono/SyliusAnalyticsPlugin#98]
### Plugin version

v1.0.0-alpha.6 # "reference": "b935843102724489cd92224a5a0657648cfa23e6"

### Sylius version

"version": "v1.11.15",   "reference": "61494235eddb173c032eb5548d69fd1035b289c9"

### What happened?

Hi , I've installed this   plugin , configured well based on docs , migration script was executed , routes path etc & created new property under GA configured GA ID along with API secret in admin panel . BUT it just trigger only page view & checkout begin triggers & following triggers are missing . 

- add_shipping_info
- add_to_cart
- begin_checkout
- purchase
- view_cart
- view_item_list
- view_item

this is how my setono_sylius_analytics.yaml looks like .
setono_google_analytics:
    gtag: ~
    # If you want to use tag manager instead of gtag, just comment the line above and remove the comment below
    # tag_manager:

can  any one help me if I'm missing missing  ?
thanks in advance

**Comment by loevgaard** [comment]
The tag bag bundle was not properly installed
